import { CustomQuery } from '../types';

export const ALL_GADGETS: CustomQuery[] = [
    {
        "id": "q-1770920776914",
        "name": "Total Ativos -",
        "sql": "SELECT COUNT(*) FROM endpoint;",
        "type": "card",
        "orientation": "vertical",
        "color": "#ffffff",
        "gridSpan": 1,
        "height": 100,
        "showLabels": true,
        "showLegend": false,
        "stackKeys": [],
        "isRounded": true,
        "rowSpan": 1,
        "titleFontSize": 10,
        "valueFontSize": 20,
        "xAxisLabelAngle": 0,
        "barSize": 20,
        "headerBgColor": "#3ca2b1",
        "valueColor": "#ffffff"
    },
    {
        "id": "q-1770922735256",
        "name": "Sistemas Operacionais",
        "sql": "SELECT operatingsystemname AS name,\n       COUNT(*) AS value\nFROM endpoint\nGROUP BY operatingsystemname\nORDER BY value DESC;\n",
        "type": "bar",
        "orientation": "vertical",
        "color": "#8b5cf6",
        "headerBgColor": "#111827",
        "labelKey": "name",
        "valueKey": "value",
        "colors": [
            "#3ca2b1"
        ],
        "isRounded": true,
        "gridSpan": 3,
        "height": 350,
        "stackKeys": [],
        "headerTextColor": "#ffffff",
        "showLabels": true,
        "showLegend": false,
        "rowSpan": 1,
        "titleFontSize": 10,
        "valueFontSize": 27,
        "xAxisLabelAngle": 0,
        "barSize": 40,
        "valueColor": "#ffffff"
    },
    {
        "id": "q-1770922994250",
        "name": "Ativos por Grupo",
        "sql": "SELECT organizationendpointgroupname AS name,\n       COUNT(*) AS value\nFROM groups\nGROUP BY organizationendpointgroupname\nORDER BY value DESC;\n",
        "type": "bar",
        "orientation": "vertical",
        "color": "#8b5cf6",
        "headerBgColor": "#111827",
        "headerTextColor": "#ffffff",
        "labelKey": "name",
        "valueKey": "value",
        "colors": [
            "#3ca2b1"
        ],
        "gridSpan": 3,
        "height": 350,
        "stackKeys": [],
        "isRounded": true,
        "rowSpan": 1,
        "titleFontSize": 15,
        "valueFontSize": 25,
        "xAxisLabelAngle": 20,
        "barSize": 20,
        "showLegend": false,
        "showLabels": true,
        "isStacked": false
    },
    {
        "id": "q-1770923040050",
        "name": "Total CVEs",
        "sql": "SELECT COUNT(*) FROM aggregation_cves;",
        "type": "card",
        "orientation": "vertical",
        "color": "#ffffff",
        "gridSpan": 1,
        "height": 59,
        "showLabels": true,
        "showLegend": false,
        "stackKeys": [],
        "isRounded": true,
        "rowSpan": 1,
        "titleFontSize": 10,
        "valueFontSize": 20,
        "xAxisLabelAngle": 0,
        "barSize": 20
    },
    {
        "id": "q-1770924026797",
        "name": "Versões Agente",
        "sql": "SELECT versionname AS name,\n       COUNT(*) AS value\nFROM endpoint\nGROUP BY versionname\nORDER BY value DESC;\n",
        "type": "bar",
        "orientation": "vertical",
        "color": "#ffffff",
        "headerBgColor": "#111827",
        "headerTextColor": "#ffffff",
        "colors": [
            "#3ca2b1"
        ],
        "gridSpan": 2,
        "height": 350,
        "stackKeys": [],
        "isRounded": true,
        "rowSpan": 1,
        "titleFontSize": 10,
        "valueFontSize": 30,
        "xAxisLabelAngle": 0,
        "barSize": 20,
        "showLegend": false,
        "showLabels": true
    },
    {
        "id": "q-vulns",
        "name": "Vulnerabilidades",
        "sql": "SELECT COUNT(*) FROM aggregation_cves;",
        "type": "card",
        "color": "#ef4444",
        "headerBgColor": "#3ca2b1",
        "headerTextColor": "#000000",
        "colors": [
            "#ffffff"
        ],
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "gridSpan": 1,
        "height": 100,
        "showLabels": true,
        "showLegend": true,
        "stackKeys": [],
        "rowSpan": 1,
        "titleFontSize": 10,
        "valueFontSize": 20
    },
    {
        "id": "q-apps",
        "name": "App Instalados",
        "sql": "SELECT COUNT(*) as value FROM products",
        "type": "card",
        "color": "#ffffff",
        "headerBgColor": "#3ca2b1",
        "headerTextColor": "#000000",
        "colors": [
            "#ffffff"
        ],
        "isRounded": true,
        "gridSpan": 1,
        "height": 100,
        "showLabels": true,
        "showLegend": true,
        "stackKeys": [],
        "rowSpan": 1,
        "titleFontSize": 10,
        "valueFontSize": 20
    },
    {
        "id": "q-connectivity",
        "name": "Status Conectividade",
        "sql": "SELECT CASE WHEN endpointalive = 1 THEN 'Online' ELSE 'Offline' END as name, COUNT(*) as value FROM endpoint GROUP BY endpointalive",
        "type": "pie",
        "color": "#10b981",
        "headerBgColor": "#111827",
        "headerTextColor": "#ffffff",
        "colors": [
            "#20ee8e",
            "#b73110"
        ],
        "valueColor": "#ffffff",
        "isRounded": true,
        "labelKey": "name",
        "valueKey": "value",
        "gridSpan": 2,
        "height": 350,
        "stackKeys": [],
        "rowSpan": 1,
        "titleFontSize": 10,
        "valueFontSize": 30,
        "xAxisLabelAngle": 0,
        "barSize": 20,
        "showLabels": true
    },
    {
        "id": "q-cve-critical",
        "name": "CVE Críticas",
        "sql": "SELECT COUNT(*) AS total_critical\nFROM aggregation_cves\nWHERE LOWER(severity) = 'critical';",
        "type": "card",
        "color": "#ffffff",
        "headerBgColor": "#dc2626",
        "headerTextColor": "#ffffff",
        "colors": [
            "#ffffff"
        ],
        "valueColor": "#ffffff",
        "isRounded": true,
        "gridSpan": 2,
        "height": 100,
        "showLabels": true,
        "showLegend": true,
        "stackKeys": [],
        "rowSpan": 1,
        "titleFontSize": 10,
        "valueFontSize": 19
    },
    {
        "id": "q-cve-high",
        "name": "CVE Altas",
        "sql": "SELECT COUNT(*) AS total_critical\nFROM aggregation_cves\nWHERE LOWER(severity) = 'high';\n",
        "type": "card",
        "color": "#ffffff",
        "headerBgColor": "#f97316",
        "headerTextColor": "#ffffff",
        "colors": [
            "#ffffff"
        ],
        "valueColor": "#ffffff",
        "isRounded": true,
        "gridSpan": 2,
        "height": 100,
        "showLabels": true,
        "showLegend": true,
        "stackKeys": [],
        "rowSpan": 1,
        "titleFontSize": 10,
        "valueFontSize": 20
    },
    {
        "id": "q-cve-medium",
        "name": "CVE Médias",
        "sql": "SELECT COUNT(*) AS total_critical\nFROM aggregation_cves\nWHERE LOWER(severity) = 'medium';\n",
        "type": "card",
        "color": "#ffffff",
        "headerBgColor": "#eab308",
        "headerTextColor": "#000000",
        "colors": [
            "#ffffff"
        ],
        "valueColor": "#ffffff",
        "isRounded": true,
        "gridSpan": 2,
        "height": 100,
        "showLabels": true,
        "showLegend": true,
        "stackKeys": [],
        "rowSpan": 1,
        "titleFontSize": 10,
        "valueFontSize": 20
    },
    {
        "id": "q-cve-low",
        "name": "CVE Baixas",
        "sql": "SELECT COUNT(*) AS total_critical\nFROM aggregation_cves\nWHERE LOWER(severity) = 'low';\n",
        "type": "card",
        "color": "#ffffff",
        "headerBgColor": "#0891b2",
        "headerTextColor": "#ffffff",
        "colors": [
            "#ffffff"
        ],
        "valueColor": "#ffffff",
        "isRounded": true,
        "gridSpan": 2,
        "height": 100,
        "showLabels": true,
        "showLegend": true,
        "stackKeys": [],
        "rowSpan": 1,
        "titleFontSize": 10,
        "valueFontSize": 20
    },
    {
        "id": "q-1770944564773",
        "name": "Licença expira em ",
        "sql": "SELECT \n    CONVERT(VARCHAR, subscriptionendedat, 103)\n    AS status_expiracao\nFROM subscriptions;\n",
        "type": "card",
        "orientation": "vertical",
        "color": "#ffffff",
        "colors": [
            "#3ca2b1"
        ],
        "headerBgColor": "#3ca2b1",
        "headerTextColor": "#000000",
        "valueColor": "#ffffff",
        "labelKey": "status_expiracao",
        "valueKey": "status_expiracao",
        "isRounded": true,
        "gridSpan": 2,
        "height": 100,
        "showLabels": true,
        "showLegend": true,
        "stackKeys": [],
        "rowSpan": 1,
        "titleFontSize": 10,
        "valueFontSize": 17
    },
    {
        "id": "q-cve-product-severity",
        "name": "Severidade por Ativo (Top 10)",
        "sql": "SELECT TOP 10\n    endpointname,\n\n    SUM(CASE WHEN severity = 'Critical' THEN 1 ELSE 0 END) AS Critical,\n    SUM(CASE WHEN severity = 'High' THEN 1 ELSE 0 END) AS High,\n    SUM(CASE WHEN severity = 'Medium' THEN 1 ELSE 0 END) AS Medium,\n    SUM(CASE WHEN severity = 'Low' THEN 1 ELSE 0 END) AS Low,\n\n    COUNT(*) AS Total\n\nFROM aggregation_cves\nGROUP BY endpointname\nORDER BY Total DESC;\n",
        "type": "bar",
        "orientation": "horizontal",
        "isStacked": false,
        "stackKeys": [
            "Critical",
            "High",
            "Medium",
            "Low"
        ],
        "colors": [
            "#dc2626",
            "#f97316",
            "#eab308",
            "#0891b2"
        ],
        "headerBgColor": "#111827",
        "headerTextColor": "#ffffff",
        "showLabels": true,
        "showLegend": true,
        "gridSpan": 2,
        "height": 600,
        "isRounded": true,
        "rowSpan": 1,
        "titleFontSize": 10,
        "valueFontSize": 30,
        "xAxisLabelAngle": 0,
        "barSize": 20
    },
    {
        "id": "q-1770948885069",
        "name": "Severidade por Produtos  (Top 10)",
        "sql": "SELECT Top 10\n    COALESCE(productname, operatingsystemname) AS name,\n\n    SUM(CASE WHEN severity = 'Critical' THEN 1 ELSE 0 END) AS Critical,\n    SUM(CASE WHEN severity = 'High' THEN 1 ELSE 0 END) AS High,\n    SUM(CASE WHEN severity = 'Medium' THEN 1 ELSE 0 END) AS Medium,\n    SUM(CASE WHEN severity = 'Low' THEN 1 ELSE 0 END) AS Low,\n\n    COUNT(*) AS Total\n\nFROM aggregation_cves\nGROUP BY COALESCE(productname, operatingsystemname)\nORDER BY Total desc;\n",
        "type": "bar",
        "orientation": "horizontal",
        "color": "#ffffff",
        "colors": [
            "#dc2626",
            "#f9731a",
            "#eab308",
            "#3ca2b1"
        ],
        "headerBgColor": "#111827",
        "headerTextColor": "#ffffff",
        "valueColor": "#ffffff",
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "isStacked": false,
        "stackKeys": [
            "Critical",
            "High",
            "Medium",
            "Low"
        ],
        "gridSpan": 3,
        "height": 700,
        "showLabels": true,
        "showLegend": true,
        "rowSpan": 1,
        "titleFontSize": 10,
        "valueFontSize": 30,
        "xAxisLabelAngle": 0,
        "barSize": 20
    },
    {
        "id": "q-1770954616169",
        "name": "Comparativo Mensal",
        "sql": "SELECT \n    DataRegistro,\n    total,\n    Critical,\n    High,\n    Medium,\n    Low\nFROM mensal\nWHERE \n    DATEFROMPARTS(\n        2000 + CAST(RIGHT(DataRegistro, 2) AS INT),  -- Ano (25 → 2025)\n        CASE LEFT(DataRegistro, CHARINDEX('/', DataRegistro) - 1)\n            WHEN 'Janeiro' THEN 1\n            WHEN 'Fevereiro' THEN 2\n            WHEN 'Março' THEN 3\n            WHEN 'Abril' THEN 4\n            WHEN 'Maio' THEN 5\n            WHEN 'Junho' THEN 6\n            WHEN 'Julho' THEN 7\n            WHEN 'Agosto' THEN 8\n            WHEN 'Setembro' THEN 9\n            WHEN 'Outubro' THEN 10\n            WHEN 'Novembro' THEN 11\n            WHEN 'Dezembro' THEN 12\n        END,\n        1\n    )\n    >= DATEADD(MONTH, -3, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1))\n\nORDER BY \n    DATEFROMPARTS(\n        2000 + CAST(RIGHT(DataRegistro, 2) AS INT),\n        CASE LEFT(DataRegistro, CHARINDEX('/', DataRegistro) - 1)\n            WHEN 'Janeiro' THEN 1\n            WHEN 'Fevereiro' THEN 2\n            WHEN 'Março' THEN 3\n            WHEN 'Abril' THEN 4\n            WHEN 'Maio' THEN 5\n            WHEN 'Junho' THEN 6\n            WHEN 'Julho' THEN 7\n            WHEN 'Agosto' THEN 8\n            WHEN 'Setembro' THEN 9\n            WHEN 'Outubro' THEN 10\n            WHEN 'Novembro' THEN 11\n            WHEN 'Dezembro' THEN 12\n        END,\n        1\n    );\n",
        "type": "bar",
        "orientation": "vertical",
        "color": "#ffffff",
        "colors": [
            "#c82626",
            "#f9731a",
            "#eab308",
            "#3ca2b1"
        ],
        "headerBgColor": "#111827",
        "headerTextColor": "#ffffff",
        "valueColor": "#ffffff",
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "isStacked": false,
        "stackKeys": [
            "Critical",
            "High",
            "Medium",
            "Low"
        ],
        "gridSpan": 4,
        "height": 300,
        "showLabels": true,
        "showLegend": true,
        "rowSpan": 2
    },
    {
        "id": "q-assets",
        "name": "Total de Ativos",
        "sql": "SELECT COUNT(*) as value FROM endpoint",
        "type": "card",
        "color": "#ffffff",
        "headerBgColor": "#0ea5e9",
        "headerTextColor": "#ffffff"
    },
    {
        "id": "q-risk",
        "name": "Score de Risco",
        "sql": "SELECT 85 as value",
        "type": "card",
        "color": "#eab308",
        "headerBgColor": "#ca8a04",
        "headerTextColor": "#ffffff"
    },
    {
        "id": "q-compliance",
        "name": "% Compliance",
        "sql": "SELECT 92 as value",
        "type": "card",
        "color": "#22c55e",
        "headerBgColor": "#16a34a",
        "headerTextColor": "#ffffff"
    },
    {
        "id": "q-os",
        "name": "Sistemas Operacionais",
        "sql": "SELECT operatingsystem as name, COUNT(*) as value FROM endpoint GROUP BY operatingsystem",
        "type": "bar",
        "orientation": "horizontal",
        "colors": [
            "#0ea5e9",
            "#38bdf8",
            "#7dd3fc"
        ],
        "headerBgColor": "#111827",
        "headerTextColor": "#0ea5e9"
    },
    {
        "id": "q-1770987066354",
        "name": "Total Mensal",
        "sql": "SELECT \n    DataRegistro,\n    total\nFROM mensal\nWHERE \n    DATEFROMPARTS(\n        2000 + CAST(RIGHT(DataRegistro, 2) AS INT),  -- Ano (25 → 2025)\n        CASE LEFT(DataRegistro, CHARINDEX('/', DataRegistro) - 1)\n            WHEN 'Janeiro' THEN 1\n            WHEN 'Fevereiro' THEN 2\n            WHEN 'Março' THEN 3\n            WHEN 'Abril' THEN 4\n            WHEN 'Maio' THEN 5\n            WHEN 'Junho' THEN 6\n            WHEN 'Julho' THEN 7\n            WHEN 'Agosto' THEN 8\n            WHEN 'Setembro' THEN 9\n            WHEN 'Outubro' THEN 10\n            WHEN 'Novembro' THEN 11\n            WHEN 'Dezembro' THEN 12\n        END,\n        1\n    )\n    >= DATEADD(MONTH, -6, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1))\n\nORDER BY \n    DATEFROMPARTS(\n        2000 + CAST(RIGHT(DataRegistro, 2) AS INT),\n        CASE LEFT(DataRegistro, CHARINDEX('/', DataRegistro) - 1)\n            WHEN 'Janeiro' THEN 1\n            WHEN 'Fevereiro' THEN 2\n            WHEN 'Março' THEN 3\n            WHEN 'Abril' THEN 4\n            WHEN 'Maio' THEN 5\n            WHEN 'Junho' THEN 6\n            WHEN 'Julho' THEN 7\n            WHEN 'Agosto' THEN 8\n            WHEN 'Setembro' THEN 9\n            WHEN 'Outubro' THEN 10\n            WHEN 'Novembro' THEN 11\n            WHEN 'Dezembro' THEN 12\n        END,\n        1\n    );\n",
        "type": "line",
        "orientation": "vertical",
        "color": "#ffffff",
        "colors": [
            "#3ca2b1"
        ],
        "headerBgColor": "#111827",
        "headerTextColor": "#ffffff",
        "valueColor": "#ffffff",
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "isStacked": false,
        "stackKeys": [
            "total"
        ],
        "gridSpan": 4,
        "height": 300,
        "showLabels": true,
        "showLegend": true,
        "rowSpan": 2,
        "titleFontSize": 10,
        "valueFontSize": 20
    },
    {
        "id": "q-1771011026881",
        "name": "Total Updates OS",
        "sql": "SELECT COUNT(DISTINCT patchid)\nFROM os_v2\nWHERE patchid IS NOT NULL\n  AND patchid <> 'sem updates';",
        "type": "card",
        "orientation": "vertical",
        "color": "#ffffff",
        "colors": [
            "#3ca2b1"
        ],
        "headerBgColor": "#3ca2b1",
        "headerTextColor": "#000000",
        "valueColor": "#ffffff",
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "isStacked": false,
        "stackKeys": [],
        "gridSpan": 3,
        "rowSpan": 1,
        "height": 220,
        "showLabels": true,
        "showLegend": false,
        "titleFontSize": 10,
        "valueFontSize": 20,
        "xAxisLabelAngle": 0,
        "barSize": 20
    },
    {
        "id": "q-1771011068176",
        "name": "Total Updates Apps",
        "sql": "SELECT COUNT(DISTINCT patchid)\nFROM app_v2\nWHERE patchid <> 'sem updates'\n   OR patchid IS NULL;\n",
        "type": "card",
        "orientation": "vertical",
        "color": "#ffffff",
        "colors": [
            "#3ca2b1"
        ],
        "headerBgColor": "#3ca2b1",
        "headerTextColor": "#000000",
        "valueColor": "#ffffff",
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "isStacked": false,
        "stackKeys": [],
        "gridSpan": 3,
        "rowSpan": 1,
        "height": 220,
        "showLabels": true,
        "showLegend": false,
        "titleFontSize": 10,
        "valueFontSize": 20,
        "xAxisLabelAngle": 0,
        "barSize": 20
    },
    {
        "id": "q-1771012209501",
        "name": "Update Por Sistema Operacionais",
        "sql": "SELECT operatingsystemname AS name,\n       COUNT(*) AS value\nFROM os_v2\nGROUP BY operatingsystemname\nORDER BY value DESC;\n",
        "type": "bar",
        "orientation": "vertical",
        "color": "#ffffff",
        "colors": [
            "#3ca2b1"
        ],
        "headerBgColor": "#111827",
        "headerTextColor": "#ffffff",
        "valueColor": "#ffffff",
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "isStacked": false,
        "stackKeys": [],
        "gridSpan": 3,
        "rowSpan": 1,
        "height": 220,
        "showLabels": true,
        "showLegend": false,
        "titleFontSize": 10,
        "valueFontSize": 27,
        "xAxisLabelAngle": 0,
        "barSize": 22
    },
    {
        "id": "q-1771012305330",
        "name": "Update Por Endpoint (OS)",
        "sql": "SELECT top 10 endpointname AS name,\n       COUNT(*) AS value\nFROM os_v2\nGROUP BY endpointname \nORDER BY value DESC;\n",
        "type": "bar",
        "orientation": "vertical",
        "color": "#ffffff",
        "colors": [
            "#3ca2b1"
        ],
        "headerBgColor": "#111827",
        "headerTextColor": "#ffffff",
        "valueColor": "#ffffff",
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "isStacked": false,
        "stackKeys": [],
        "gridSpan": 3,
        "rowSpan": 1,
        "height": 220,
        "showLabels": true,
        "showLegend": false,
        "titleFontSize": 10,
        "valueFontSize": 28,
        "xAxisLabelAngle": 27,
        "barSize": 20
    },
    {
        "id": "q-1771012410111",
        "name": "Update Por App",
        "sql": "SELECT top 10 productname AS name,\n       COUNT(*) AS value\nFROM app_v2\nGROUP BY productname\nORDER BY value DESC;\n",
        "type": "bar",
        "orientation": "vertical",
        "color": "#ffffff",
        "colors": [
            "#3ca2b1"
        ],
        "headerBgColor": "#111827",
        "headerTextColor": "#ffffff",
        "valueColor": "#ffffff",
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "isStacked": false,
        "stackKeys": [],
        "gridSpan": 3,
        "rowSpan": 1,
        "height": 220,
        "showLabels": true,
        "showLegend": false,
        "titleFontSize": 10,
        "valueFontSize": 27,
        "xAxisLabelAngle": 0,
        "barSize": 20
    },
    {
        "id": "q-1771012496236",
        "name": "Update Por Endpoint (APPs)",
        "sql": "SELECT TOP 10 \n       endpointname AS name,\n       COUNT(*) AS value\nFROM app_v2\nWHERE endpointname <> 'sem updates'\nGROUP BY endpointname \nORDER BY value DESC;\n",
        "type": "bar",
        "orientation": "vertical",
        "color": "#ffffff",
        "colors": [
            "#3ca2b1"
        ],
        "headerBgColor": "#111827",
        "headerTextColor": "#3ca2b1",
        "valueColor": "#ffffff",
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "isStacked": false,
        "stackKeys": [],
        "gridSpan": 3,
        "rowSpan": 1,
        "height": 220,
        "showLabels": true,
        "showLegend": false,
        "titleFontSize": 10,
        "valueFontSize": 29,
        "xAxisLabelAngle": 15,
        "barSize": 14
    },
    {
        "id": "q-pending-patches",
        "name": "Patches Pendentes",
        "sql": "SELECT 152 as value",
        "type": "card",
        "color": "#38bdf8",
        "headerBgColor": "#0369a1",
        "gridSpan": 3,
        "rowSpan": 1
    },
    {
        "id": "q-softwares-update",
        "name": "Softwares que requerem Update",
        "sql": "SELECT TOP 10 endpointname as App, cvecount as Vulnerabilidades FROM endpoint ORDER BY cvecount DESC",
        "type": "table",
        "gridSpan": 12,
        "rowSpan": 1.5
    },
    {
        "id": "q-1771722966647",
        "name": "Pendentes vs Atualizados por Sistema Operacional",
        "sql": "DECLARE @colAtualizados NVARCHAR(50) = 'Atualizados';\nDECLARE @colPendentes NVARCHAR(50) = 'Pendentes';\nDECLARE @sql NVARCHAR(MAX);\n\nSET @sql = '\nSELECT \n    a.operatingsystemname AS sistema_operacional,\n    a.assets - COALESCE(p.pendentes, 0) AS ' + QUOTENAME(@colAtualizados) + ',\n    COALESCE(p.pendentes, 0) AS ' + QUOTENAME(@colPendentes) + '\nFROM assets_os a\nLEFT JOIN pendentes_os p\n    ON a.operatingsystemname = p.operatingsystemname\nORDER BY a.operatingsystemname;';\n\nEXEC sp_executesql @sql;",
        "type": "bar",
        "orientation": "vertical",
        "color": "#ffffff",
        "colors": [
            "#c7c248",
            "#3caf64"
        ],
        "headerBgColor": "#111827",
        "headerTextColor": "#ffffff",
        "valueColor": "#ffffff",
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "isStacked": false,
        "stackKeys": [
            "Pendentes",
            "Atualizados"
        ],
        "gridSpan": 3,
        "rowSpan": 1,
        "height": 260,
        "showLabels": true,
        "showLegend": false,
        "titleFontSize": 10,
        "valueFontSize": 30,
        "xAxisLabelAngle": 15,
        "barSize": 20
    },
    {
        "id": "q-1771723201985",
        "name": "Status Assets Atalizações",
        "sql": "SELECT \n    name,\n    SUM(value) as value\nFROM (\n    SELECT 'Pendentes' AS name, SUM(ISNULL(pendentes,0)) AS value\n    FROM pendentes_os\n\n    UNION ALL\n\n    SELECT 'Atualizados',\n           SUM(ISNULL(assets,0)) \n           - (SELECT SUM(ISNULL(pendentes,0)) FROM pendentes_os)\n    FROM assets_os\n) x\nGROUP BY name;",
        "type": "pie",
        "orientation": "vertical",
        "color": "#ffffff",
        "colors": [
            "#3caf49",
            "#9ba83e"
        ],
        "headerBgColor": "#111827",
        "headerTextColor": "#ffffff",
        "valueColor": "#ffffff",
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "isStacked": false,
        "stackKeys": [],
        "gridSpan": 3,
        "rowSpan": 1,
        "height": 260,
        "showLabels": true,
        "showLegend": true,
        "titleFontSize": 10,
        "valueFontSize": 30,
        "xAxisLabelAngle": 0,
        "barSize": 20
    },
    {
        "id": "q-1771723881418",
        "name": "Tabela ",
        "sql": "SELECT \n    a.operatingsystemname,\n    SUM(ISNULL(a.assets,0)) AS Total_Assets,\n    SUM(ISNULL(p.pendentes,0)) AS Total_Pendentes,\n    SUM(ISNULL(a.assets,0)) - SUM(ISNULL(p.pendentes,0)) AS Assets_Atualizados\nFROM assets_os a\nLEFT JOIN pendentes_os p\n    ON LTRIM(RTRIM(a.operatingsystemname)) = LTRIM(RTRIM(p.operatingsystemname))\nGROUP BY a.operatingsystemname\nORDER BY a.operatingsystemname;",
        "type": "table",
        "orientation": "vertical",
        "color": "#ffffff",
        "colors": [
            "#3ca2b1"
        ],
        "headerBgColor": "#111827",
        "headerTextColor": "#ffffff",
        "valueColor": "#ffffff",
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "isStacked": false,
        "stackKeys": [],
        "gridSpan": 3,
        "rowSpan": 1,
        "height": 220,
        "showLabels": true,
        "showLegend": false,
        "titleFontSize": 10,
        "valueFontSize": 35,
        "xAxisLabelAngle": 0,
        "barSize": 20
    },
    {
        "id": "q-1771946063571",
        "name": "Total Ativo",
        "sql": "SELECT COUNT(*) FROM endpoint;",
        "type": "card",
        "orientation": "vertical",
        "color": "#ffffff",
        "colors": [
            "#3ca2b1"
        ],
        "headerBgColor": "#3ca2b1",
        "headerTextColor": "#000000",
        "valueColor": "#ffffff",
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "isStacked": false,
        "stackKeys": [],
        "gridSpan": 3,
        "rowSpan": 1,
        "height": 220,
        "showLabels": true,
        "showLegend": true,
        "titleFontSize": 10,
        "valueFontSize": 30,
        "xAxisLabelAngle": 0,
        "barSize": 20
    },
    {
        "id": "q-1771952429199",
        "name": "Total auto Action",
        "sql": "SELECT \n    COUNT(DISTINCT automation_name) AS total_automations\nFROM task_events\nWHERE TRY_CONVERT(datetime, automation_created_at, 103) \n      >= DATEADD(DAY, -30, GETDATE());",
        "type": "card",
        "orientation": "vertical",
        "color": "#ffffff",
        "colors": [
            "#3ca2b1"
        ],
        "headerBgColor": "#3ca2b1",
        "headerTextColor": "#000000",
        "valueColor": "#ffffff",
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "isStacked": false,
        "stackKeys": [],
        "gridSpan": 3,
        "rowSpan": 1,
        "height": 220,
        "showLabels": true,
        "showLegend": true,
        "titleFontSize": 10,
        "valueFontSize": 30,
        "xAxisLabelAngle": 0,
        "barSize": 20
    },
    {
        "id": "q-1771954745381",
        "name": "Tasks por tipo (últimos 30 dias)",
        "sql": "SELECT \n    name,\n    COUNT(*) AS value\nFROM (\n    SELECT \n        CASE \n            WHEN task_type = 'ApplyPublisherOperatingSystemVersionsPatchs' \n                THEN 'UpdatesOS'\n            WHEN task_type = 'ApplyPublisherProductVersionsPatchs' \n                THEN 'UpdatesApps'\n            ELSE task_type\n        END AS name\n    FROM task_events\n    WHERE TRY_CONVERT(datetime, automation_created_at) \n          >= DATEADD(DAY, -30, GETDATE())\n) t\nGROUP BY name\nORDER BY value DESC;",
        "type": "pie",
        "orientation": "vertical",
        "color": "#ffffff",
        "colors": [
            "#329dae",
            "#8e5991",
            "#2a503b"
        ],
        "headerBgColor": "#3ca2b1",
        "headerTextColor": "#000000",
        "valueColor": "#ffffff",
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "isStacked": false,
        "stackKeys": [],
        "gridSpan": 3,
        "rowSpan": 1,
        "height": 220,
        "showLabels": true,
        "showLegend": true,
        "titleFontSize": 10,
        "valueFontSize": 30,
        "xAxisLabelAngle": 0,
        "barSize": 20
    },
    {
        "id": "q-1771954937854",
        "name": "Tasks por usuário",
        "sql": "SELECT \n    task_user AS [Usuário],\n    COUNT(DISTINCT automation_name) AS [Total de Action]\nFROM task_events\nWHERE TRY_CONVERT(datetime, automation_created_at) IS NOT NULL\n  AND TRY_CONVERT(datetime, automation_created_at) \n      >= DATEADD(DAY, -30, GETDATE())\nGROUP BY task_user\nORDER BY [Total de Action] DESC;",
        "type": "table",
        "orientation": "vertical",
        "color": "#ffffff",
        "colors": [
            "#3ca2b1"
        ],
        "headerBgColor": "#3ca2b1",
        "headerTextColor": "#000000",
        "valueColor": "#ffffff",
        "labelKey": "",
        "valueKey": "",
        "isRounded": true,
        "isStacked": false,
        "stackKeys": [],
        "gridSpan": 3,
        "rowSpan": 1,
        "height": 220,
        "showLabels": true,
        "showLegend": false,
        "titleFontSize": 10,
        "valueFontSize": 30,
        "xAxisLabelAngle": 0,
        "barSize": 20
    }
];
